### PR TITLE
Adjust all posix permission changes and set access to 744

### PR DESCRIPTION
**Pull request by xBis7**
I've run all tests and they are still passing.

### CODE REVIEW

**Comment by GeorgeJahad** [comment]
should this be changed:
https://github.com/xBis7/docker-setup-helper-scripts/blob/bb517b9aea61dd73e371a055b5c28bb4a443661d/trino-hms-hdfs-ranger/big-data-c3-tests/trino-spark-tests/spark/test_6.sh#L16-L17

**Comment by xBis7** [comment]
> should this be changed:
> [docker-setup-helper-scripts/trino-hms-hdfs-ranger/big-data-c3-tests/trino-spark-tests/spark/test_6.sh](https://github.com/xBis7/docker-setup-helper-scripts/blob/bb517b9aea61dd73e371a055b5c28bb4a443661d/trino-hms-hdfs-ranger/big-data-c3-tests/trino-spark-tests/spark/test_6.sh#L16-L17)
> 
> Lines 16 to 17 in [bb517b9](https://github.com/xBis7/docker-setup-helper-scripts/commit/bb517b9aea61dd73e371a055b5c28bb4a443661d)
> 
>  changeHdfsDirPermissions "$HIVE_WAREHOUSE_PARENT_DIR" 755 
>  changeHdfsDirPermissions "$HIVE_WAREHOUSE_DIR" 755

I thought about it but the BigData notes for Spark test 6, are explicitly setting the permissions for the HiveWarehouse directory to 755. That's why this change is in test 6 and not in the setup.

**Comment by GeorgeJahad** [comment]
> the BigData notes for Spark test 6, are explicitly setting the permissions

ok, then please add a comment saying that to test 6.

**Comment by xBis7** [comment]
@GeorgeJahad I added the comment.

**Review by GeorgeJahad — APPROVED** [review]
lgtm

**Comment by xBis7** [comment]
@GeorgeJahad Thanks!

**Pull request merged**
