### PR TITLE
Hive/Ranger commit SHA update

### PR DESCRIPTION
**Pull request by xBis7**

### CODE REVIEW

**Comment by mladjan-gadzic** [comment]
Please, remind me, I've forgotten, is this the effort to make Ranger usable locally because it's known that it gets stuck at change user/password screen?

I haven't checked, but I am curious, is Ranger 2.4.0 still supported by Ranger community? If it is, do you think it makes sense to bring this there?

**Comment by xBis7** [comment]
No this is related to fixing all failing unit tests in Hive. After upgrading the Hadoop version in Hive to 3.3.6, we didn't run the unit tests. Due to the update many of them were failing.

Check this PR

https://github.com/xBis7/hive/pull/6

The Ranger issue has been fixed and the current Ranger commit SHA points to the fix.

**Comment by mladjan-gadzic** [comment]
> The Ranger issue has been fixed and the current Ranger commit SHA points to the fix.

Not sure how I've missed that. I'll try it on my Intel arch MBP.

I've noticed that this PR has to do with dependencies but I am not famialiar with the work. That's why I've asked. I guess @GeorgeJahad would be the right reviewer for this since he reviewed https://github.com/xBis7/hive/pull/6.

**Comment by xBis7** [comment]
I've updated this PR and removed all the jetty-runner-shaded changes because I found a way to make the changes under the Hive project. This PR will be used just for updating the Hive commit SHA.

There will be a Hive PR and after it's merged, this one will be updated with the new Hive SHA and will be moved out of draft.

**Comment by xBis7** [comment]
@mladjan-gadzic Can you take a look?

**Comment by mladjan-gadzic** [comment]
Thanks @xBis7 !

**Pull request merged**
