### PR TITLE
Merge to stable

### PR DESCRIPTION
**Pull request by mladjan-gadzic**
IMO all of these are stable changes

### CODE REVIEW

**Comment by xBis7** [comment]
@mladjan-gadzic Did you use a rebase or a merge?

**Comment by xBis7** [comment]
> I've created a PR from master to stable branch just using GitHub UI. For merge options I'd use Rebase and merge.

I think that's fine. It will keep the history linear and all the commits will be visible.

**Review by xBis7 — APPROVED** [review]
@mladjan-gadzic Thanks! Merge it, when you are ready.

**Comment by mladjan-gadzic** [comment]
@xBis7 thanks for the review, going to merge it!

**Pull request merged**
